name : Master Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Install & build
        run: |
          sudo apt-get update

          # install java
          sudo apt-get install wget make openjdk-8-jdk-headless

          # compile antlr4 sources
          cd ${GITHUB_WORKSPACE}
          make

          # install sbt
          echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
          sudo apt-get install -y sbt

      - name: Unit Tests
        run: |
          sbt test

      - name: Scala formatting
        run: |
          sbt scalafmtCheckAll
